"""
Squad and SquadMembership data models.

Implements Requirements 2.5, 2.6 (Squad matching and formation).
"""
from datetime import datetime
from typing import Optional
from uuid import uuid4
from sqlalchemy import Column, String, Integer, Float, DateTime, ForeignKey, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from enum import Enum
from app.db.base import Base


class SquadStatus(str, Enum):
    """Status of squad."""
    FORMING = "forming"      # < 12 members
    ACTIVE = "active"        # 12-15 members, learning in progress
    COMPLETED = "completed"  # Finished 30-day cycle


class Squad(Base):
    """
    Squad model for matched groups of 12-15 learners within a guild.
    
    Squads are formed by the Node Logic matching engine based on cognitive compatibility.
    Each squad has a dedicated chat channel and follows a 30-day syllabus generated by
    the Guild Master AI.
    
    Implements Requirements:
    - 2.5: Squad activation at threshold (12 members)
    - 2.6: Squad size constraints (12-15 members)
    """
    __tablename__ = "squads"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4, index=True)
    guild_id = Column(UUID(as_uuid=True), ForeignKey("guilds.id", ondelete="CASCADE"), nullable=False, index=True)
    name = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    status = Column(SQLEnum(SquadStatus), nullable=False, default=SquadStatus.FORMING)
    
    # Member tracking
    member_count = Column(Integer, default=0, nullable=False)
    
    # Learning progress
    current_syllabus_id = Column(UUID(as_uuid=True), nullable=True)  # Reference to current syllabus
    syllabus_start_date = Column(DateTime, nullable=True)
    current_day = Column(Integer, default=0, nullable=False)  # 0-30, 0 means not started
    
    # Chat integration
    chat_channel_id = Column(String, nullable=True)  # Firebase/Supabase channel ID
    
    # Analytics
    average_completion_rate = Column(Float, default=0.0, nullable=False)  # 0.0-1.0
    average_skill_level = Column(Float, default=0.0, nullable=False)  # Average of member skill levels
    
    # Relationships
    guild = relationship("Guild", back_populates="squads")
    memberships = relationship("SquadMembership", back_populates="squad", cascade="all, delete-orphan")
    
    def __repr__(self) -> str:
        return f"<Squad(id={self.id}, name={self.name}, status={self.status}, members={self.member_count})>"


class SquadMembership(Base):
    """
    Squad membership model for tracking user membership in squads.
    
    Links users to squads and tracks when they joined.
    """
    __tablename__ = "squad_memberships"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    squad_id = Column(UUID(as_uuid=True), ForeignKey("squads.id", ondelete="CASCADE"), nullable=False, index=True)
    joined_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    user = relationship("User", backref="squad_memberships")
    squad = relationship("Squad", back_populates="memberships")
    
    def __repr__(self) -> str:
        return f"<SquadMembership(user_id={self.user_id}, squad_id={self.squad_id})>"
