"""
Syllabus, SyllabusDay, Task, and Resource data models.

Implements Requirements 3.1, 3.2 (AI Guild Master syllabus generation).
"""
from datetime import datetime
from typing import Optional
from uuid import uuid4
from sqlalchemy import Column, String, Integer, Float, DateTime, ForeignKey, Boolean, Text, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID, ARRAY, JSON
from sqlalchemy.orm import relationship
from enum import Enum
from app.db.base import Base


class TaskType(str, Enum):
    """Type of learning task."""
    READING = "reading"
    CODING = "coding"
    PROJECT = "project"
    QUIZ = "quiz"


class ResourceType(str, Enum):
    """Type of learning resource."""
    ARTICLE = "article"
    VIDEO = "video"
    DOCUMENTATION = "documentation"
    TUTORIAL = "tutorial"
    BOOK = "book"
    COURSE = "course"


class Syllabus(Base):
    """
    Syllabus model for 30-day learning roadmaps generated by Guild Master AI.
    
    Each squad has a syllabus that defines their learning path with daily
    objectives, tasks, and resources. Syllabi can be pivoted based on squad
    performance.
    
    Implements Requirements:
    - 3.1: Guild Master generates 30-day syllabus
    - 3.2: Syllabus includes daily objectives, resources, and milestones
    """
    __tablename__ = "syllabi"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4, index=True)
    squad_id = Column(UUID(as_uuid=True), ForeignKey("squads.id", ondelete="CASCADE"), nullable=False, index=True)
    version = Column(Integer, default=1, nullable=False)  # Increments on pivot
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    created_by = Column(String, default="guild_master_ai", nullable=False)  # "guild_master_ai" or user_id
    
    # Content
    learning_objectives = Column(ARRAY(String), nullable=False)  # Overall learning objectives
    
    # Metadata
    difficulty_level = Column(Integer, nullable=False)  # 1-10 scale
    estimated_hours_per_day = Column(Float, nullable=False)  # Average hours per day
    
    # Status tracking
    is_active = Column(Boolean, default=True, nullable=False)  # Current active syllabus
    last_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Pivot tracking
    pivot_reason = Column(Text, nullable=True)  # Reason for pivot if this is a pivoted syllabus
    previous_syllabus_id = Column(UUID(as_uuid=True), ForeignKey("syllabi.id"), nullable=True)  # Reference to previous version
    
    # Relationships
    squad = relationship("Squad", backref="syllabi")
    days = relationship("SyllabusDay", back_populates="syllabus", cascade="all, delete-orphan", order_by="SyllabusDay.day_number")
    previous_syllabus = relationship("Syllabus", remote_side=[id], uselist=False)
    
    def __repr__(self) -> str:
        return f"<Syllabus(id={self.id}, squad_id={self.squad_id}, version={self.version}, difficulty={self.difficulty_level})>"


class SyllabusDay(Base):
    """
    Syllabus day model for individual days in a 30-day syllabus.
    
    Each day contains learning objectives, tasks, and resources.
    Days are unlocked sequentially as squad progresses.
    """
    __tablename__ = "syllabus_days"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4, index=True)
    syllabus_id = Column(UUID(as_uuid=True), ForeignKey("syllabi.id", ondelete="CASCADE"), nullable=False, index=True)
    day_number = Column(Integer, nullable=False)  # 1-30
    title = Column(String, nullable=False)
    
    # Content
    learning_objectives = Column(ARRAY(String), nullable=False)  # Daily learning objectives
    
    # Unlocking
    unlock_date = Column(DateTime, nullable=True)  # When this day becomes available
    is_unlocked = Column(Boolean, default=False, nullable=False)
    
    # Completion tracking
    completion_count = Column(Integer, default=0, nullable=False)  # Number of squad members who completed
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    syllabus = relationship("Syllabus", back_populates="days")
    tasks = relationship("Task", back_populates="syllabus_day", cascade="all, delete-orphan", order_by="Task.order_index")
    resources = relationship("Resource", back_populates="syllabus_day", cascade="all, delete-orphan")
    
    def __repr__(self) -> str:
        return f"<SyllabusDay(id={self.id}, day_number={self.day_number}, title={self.title})>"


class Task(Base):
    """
    Task model for learning tasks within a syllabus day.
    
    Tasks can be reading, coding exercises, projects, or quizzes.
    Each task has an estimated time and can be required or optional.
    """
    __tablename__ = "tasks"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4, index=True)
    syllabus_day_id = Column(UUID(as_uuid=True), ForeignKey("syllabus_days.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Content
    title = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    task_type = Column(SQLEnum(TaskType), nullable=False)
    
    # Metadata
    estimated_minutes = Column(Integer, nullable=False)  # Estimated time to complete
    required = Column(Boolean, default=True, nullable=False)  # Required vs optional
    order_index = Column(Integer, nullable=False)  # Order within the day
    
    # Additional data (e.g., quiz questions, code templates)
    additional_data = Column(JSON, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    syllabus_day = relationship("SyllabusDay", back_populates="tasks")
    
    def __repr__(self) -> str:
        return f"<Task(id={self.id}, title={self.title}, type={self.task_type}, required={self.required})>"


class Resource(Base):
    """
    Resource model for learning resources attached to syllabus days.
    
    Resources include articles, videos, documentation, tutorials, etc.
    """
    __tablename__ = "resources"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4, index=True)
    syllabus_day_id = Column(UUID(as_uuid=True), ForeignKey("syllabus_days.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Content
    title = Column(String, nullable=False)
    url = Column(String, nullable=False)
    resource_type = Column(SQLEnum(ResourceType), nullable=False)
    
    # Metadata
    description = Column(Text, nullable=True)  # Optional description
    estimated_minutes = Column(Integer, nullable=True)  # Estimated time to consume
    author = Column(String, nullable=True)  # Author or creator
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    syllabus_day = relationship("SyllabusDay", back_populates="resources")
    
    def __repr__(self) -> str:
        return f"<Resource(id={self.id}, title={self.title}, type={self.resource_type})>"


class TaskCompletion(Base):
    """
    Task completion model for tracking user task completions.
    
    Used for learning velocity tracking and progress monitoring.
    Implements Requirement 4.1: Record task completion timestamps.
    """
    __tablename__ = "task_completions"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    task_id = Column(UUID(as_uuid=True), ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False, index=True)
    squad_id = Column(UUID(as_uuid=True), ForeignKey("squads.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Completion data
    completed_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    time_spent_minutes = Column(Integer, nullable=True)  # Optional: actual time spent
    
    # Quality metrics
    quality_score = Column(Float, nullable=True)  # Optional: quality of completion (0-1)
    notes = Column(Text, nullable=True)  # Optional: user notes
    
    # Relationships
    user = relationship("User", backref="task_completions")
    task = relationship("Task", backref="completions")
    squad = relationship("Squad", backref="task_completions")
    
    def __repr__(self) -> str:
        return f"<TaskCompletion(user_id={self.user_id}, task_id={self.task_id}, completed_at={self.completed_at})>"
